const state={data:null,view:'overview',filters:{year:'all',gender:'all',location:'all'},charts:[]};
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
const number=v=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(v||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){const response=await fetch('../data/cleaned/dashboard_data.json');state.data=await response.json();document.getElementById('date-range').textContent=`${state.data.kpis.date_start} — ${state.data.kpis.date_end}`;populateFilters();render();}
function populateFilters(){const d=state.data;const years=[...new Set(d.monthly.map(x=>x.month.slice(0,4)))];document.getElementById('year-filter').innerHTML='<option value="all">All years</option>'+years.map(x=>`<option>${x}</option>`).join('');document.getElementById('gender-filter').innerHTML='<option value="all">All genders</option>'+d.genders.map(x=>`<option value="${esc(x.customer_gender)}">${esc(x.customer_gender)}</option>`).join('');document.getElementById('location-filter').innerHTML='<option value="all">All locations</option>'+d.locations.map(x=>`<option value="${esc(x.customer_location)}">${esc(x.customer_location)}</option>`).join('');['year','gender','location'].forEach(key=>document.getElementById(`${key}-filter`).addEventListener('change',e=>{state.filters[key]=e.target.value;render()}));document.getElementById('reset').onclick=()=>{state.filters={year:'all',gender:'all',location:'all'};populateFilters();render()};document.getElementById('refresh').onclick=()=>load()}
function matches(row){return (state.filters.year==='all'||String(row.transaction_year)===state.filters.year)&&(state.filters.gender==='all'||row.customer_gender===state.filters.gender)&&(state.filters.location==='all'||row.customer_location===state.filters.location)}
function aggregate(rows,key,fields){return rows.reduce((result,row)=>{const current=result.find(item=>item[key]===row[key]);if(current)fields.forEach(field=>current[field]=(current[field]||0)+(row[field]||0));else result.push({...row});return result},[])}
function filteredCustomerCount(){const f=state.filters,c=state.data.customer_counts;const find=(rows,keys)=>{const row=rows.find(item=>keys.every(([key,value])=>String(item[key])===value));return row?row.customer_count:0};const hasYear=f.year!=='all',hasGender=f.gender!=='all',hasLocation=f.location!=='all';if(hasYear&&hasGender&&hasLocation)return find(c.year_gender_location,[['transaction_year',f.year],['customer_gender',f.gender],['customer_location',f.location]]);if(hasYear&&hasGender)return find(c.year_gender,[['transaction_year',f.year],['customer_gender',f.gender]]);if(hasYear&&hasLocation)return find(c.year_location,[['transaction_year',f.year],['customer_location',f.location]]);if(hasGender&&hasLocation)return find(c.gender_location,[['customer_gender',f.gender],['customer_location',f.location]]);if(hasYear)return find(c.year,[['transaction_year',f.year]]);if(hasGender)return find(c.gender,[['customer_gender',f.gender]]);if(hasLocation)return find(c.location,[['customer_location',f.location]]);return state.data.kpis.customers}
function activeData(){const base=state.data;const noFilters=Object.values(state.filters).every(value=>value==='all');const segments=base.segments.filter(matches);const totals=segments.reduce((a,x)=>({transaction_count:a.transaction_count+x.transaction_count,total_value:a.total_value+x.total_value,customer_count:a.customer_count+x.customer_count}),{transaction_count:0,total_value:0,customer_count:0});const monthly=aggregate(base.segment_monthly.filter(matches),'month',['transaction_count','total_value']).map(x=>({...x,total_transaction_amount_inr:x.total_value})).sort((a,b)=>a.month.localeCompare(b.month));const hourly=aggregate(base.segment_hourly.filter(matches),'transaction_hour',['transaction_count','total_value']).map(x=>({...x,total_transaction_amount_inr:x.total_value})).sort((a,b)=>a.transaction_hour-b.transaction_hour);const allLocations=aggregate(segments,'customer_location',['transaction_count','total_value','customer_count']).map(x=>({...x,total_transaction_amount_inr:x.total_value,average_transaction_amount_inr:x.total_value/x.transaction_count})).sort((a,b)=>b.total_value-a.total_value);const locations=allLocations.slice(0,12);totals.customer_count=filteredCustomerCount();const filteredKpis=noFilters?base.kpis:{...base.kpis,transactions:totals.transaction_count,customers:totals.customer_count,total_value:totals.total_value,average_value:totals.transaction_count?totals.total_value/totals.transaction_count:0};const filteredRows=rows=>rows.filter(matches);const genders=state.filters.location==='all'?base.genders:aggregate(filteredRows(base.segment_genders),'customer_gender',['customer_count','transaction_count','total_value']);const age_groups=aggregate(filteredRows(base.segment_age_groups),'age_group',['transaction_count','total_value']);const value_groups=aggregate(filteredRows(base.segment_value_groups),'transaction_value_group',['transaction_count','total_value']);const distribution=aggregate(filteredRows(base.segment_distribution),'amount_bin',['transaction_count']);const customers=(noFilters?base.customers:filteredRows(base.segment_customers)).sort((a,b)=>b.total_transaction_amount_inr-a.total_transaction_amount_inr);return {...base,kpis:filteredKpis,monthly,hourly,locations,allLocations,genders,age_groups,value_groups,distribution,customers}}
function chart(id,type,labels,datasets,options={}){const ctx=document.getElementById(id);if(!ctx)return;state.charts.push(new Chart(ctx,{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:datasets.length>1,position:'bottom',labels:{boxWidth:10,font:{size:10}}}},scales:{x:{grid:{display:false},ticks:{font:{size:10}}},y:{grid:{color:'#edf1f0'},ticks:{font:{size:10}}}},...options}}))}
function kpis(){const d=activeData(),k=d.kpis;return `<section class="kpi-grid"><div class="kpi"><span class="kpi-label">Total customers</span><div class="kpi-value">${number(k.customers)}</div><span class="kpi-note">Derived from transaction records</span></div><div class="kpi"><span class="kpi-label">Total transactions</span><div class="kpi-value">${number(k.transactions)}</div><span class="kpi-note">Filtered transaction rows</span></div><div class="kpi"><span class="kpi-label">Transaction value</span><div class="kpi-value">${money(k.total_value)}</div><span class="kpi-note">Gross transaction amount</span></div><div class="kpi"><span class="kpi-label">Average transaction</span><div class="kpi-value">${money(k.average_value)}</div><span class="kpi-note">Overall median ${money(state.data.kpis.median_value)} | P95 ${money(state.data.quality.percentiles_inr['95'])}</span></div></section>`}
function panel(title,sub,id,wide=false){return `<article class="panel ${wide?'wide':''}"><div class="panel-head"><div><h2>${title}</h2><p>${sub}</p></div></div><div class="chart-wrap"><canvas id="${id}"></canvas></div></article>`}
function insights(){return `<div class="insights">${state.data.insights.map(x=>`<div class="insight"><strong>${esc(x.label)}</strong>${esc(x.value)}</div>`).join('')}</div>`}
function overview(){return kpis()+`<div class="grid">${panel('Transaction trend during the available period','October is partial through October 21; do not interpret it as a full-month decline.','monthly-chart',true)}${panel('Top locations','Leading locations by transaction value.','location-chart')}</div>${insights()}<div class="quality"><strong>Data quality</strong><span>${number(state.data.quality.source_rows)} raw rows analyzed</span><span>${number(state.data.quality.invalid_dob_values_set_missing)} suspicious DOBs converted to missing</span><span>${state.data.quality.iqr_outlier_count.toLocaleString()} IQR outliers above ${money(state.data.quality.iqr_upper_outlier_threshold_inr)}</span><span>${state.data.quality.duplicate_transaction_ids} duplicate transaction IDs</span></div>`}
function customers(){return `<div class="grid">${panel('Customer value leaders','Top customers ranked by total transaction value.','customer-chart',true)}${panel('Customer mix by gender','Unique customers and transaction volume.','gender-chart')}</div><div class="grid">${panel('Age group activity','Transactions by validated customer age group.','age-chart')}${panel('Transaction value bands','Distribution based on dataset quartiles.','value-chart')}</div>`}
function transactions(){return `<div class="grid">${panel('Transaction activity by hour','Count of transactions by hour of day.','hour-chart',true)}${panel('Transaction distribution','Count of records in each amount band.','distribution-chart')}</div><div class="grid">${panel('Monthly transaction count','Available-period volume; October is partial through October 21.','monthly-count-chart',true)}${panel('Percentile profile','The mean is above the median because larger transactions pull the average upward.','stats-panel')}</div>`}
function geography(){const d=activeData();return `<div class="grid">${panel('Location value leaders','Top 12 locations by total transaction value.','location-chart',true)}${panel('Location customer reach','Unique customers at leading locations.','location-count-chart')}</div><div class="panel wide"><div class="panel-head"><div><h2>Location performance table</h2><p>Count, value, and average transaction by location.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Location</th><th>Customers</th><th>Transactions</th><th>Total value</th><th>Average</th></tr></thead><tbody>${d.allLocations.map(x=>`<tr><td>${esc(x.customer_location)}</td><td>${number(x.customer_count)}</td><td>${number(x.transaction_count)}</td><td>${money(x.total_transaction_amount_inr)}</td><td>${money(x.average_transaction_amount_inr)}</td></tr>`).join('')}</tbody></table></div></div>`}
function render(){state.charts.forEach(c=>c.destroy());state.charts=[];const titles={overview:'Executive overview',customers:'Customer analytics',transactions:'Transaction analytics',geography:'Geographic analysis'};document.getElementById('page-title').textContent=titles[state.view];const app=document.getElementById('app');app.innerHTML=({overview,customers,transactions,geography}[state.view])();const d=activeData();
 if(document.getElementById('monthly-chart'))chart('monthly-chart','line',d.monthly.map(x=>x.month),[{label:'Total value',data:d.monthly.map(x=>x.total_transaction_amount_inr),borderColor:'#0c7773',backgroundColor:'rgba(12,119,115,.12)',fill:true,tension:.3}]);
 if(document.getElementById('monthly-count-chart'))chart('monthly-count-chart','line',d.monthly.map(x=>x.month),[{label:'Transactions',data:d.monthly.map(x=>x.transaction_count),borderColor:'#3f7196',tension:.3}]);
 if(document.getElementById('location-chart'))chart('location-chart','bar',d.locations.map(x=>x.customer_location),[{label:'Value',data:d.locations.map(x=>x.total_transaction_amount_inr),backgroundColor:'#e7894b',borderRadius:3}],{indexAxis:'y',scales:{x:{grid:{color:'#edf1f0'}},y:{grid:{display:false},ticks:{font:{size:9}}}}});
 if(document.getElementById('location-count-chart'))chart('location-count-chart','bar',d.locations.map(x=>x.customer_location),[{label:'Customers',data:d.locations.map(x=>x.customer_count),backgroundColor:'#3f7196',borderRadius:3}],{indexAxis:'y',scales:{x:{grid:{color:'#edf1f0'}},y:{grid:{display:false},ticks:{font:{size:9}}}}});
 if(document.getElementById('customer-chart'))chart('customer-chart','bar',d.customers.slice(0,10).map(x=>x.customer_id),[{label:'Value',data:d.customers.slice(0,10).map(x=>x.total_transaction_amount_inr),backgroundColor:'#0c7773',borderRadius:3}],{indexAxis:'y',scales:{x:{grid:{color:'#edf1f0'}},y:{grid:{display:false}}}});
 if(document.getElementById('gender-chart'))chart('gender-chart','doughnut',d.genders.map(x=>x.customer_gender),[{data:d.genders.map(x=>x.customer_count),backgroundColor:['#0c7773','#e7894b','#9aa9b1'],borderWidth:0}],{plugins:{legend:{display:true,position:'bottom'}}});
 if(document.getElementById('age-chart'))chart('age-chart','bar',d.age_groups.map(x=>x.age_group),[{label:'Transactions',data:d.age_groups.map(x=>x.transaction_count),backgroundColor:'#3f7196',borderRadius:3}],{scales:{x:{grid:{display:false}},y:{grid:{color:'#edf1f0'}}}});
 if(document.getElementById('value-chart'))chart('value-chart','doughnut',d.value_groups.map(x=>x.transaction_value_group),[{data:d.value_groups.map(x=>x.transaction_count),backgroundColor:['#9bb6aa','#e7894b','#193a4a'],borderWidth:0}],{plugins:{legend:{display:true,position:'bottom'}}});
 if(document.getElementById('distribution-chart'))chart('distribution-chart','bar',d.distribution.map(x=>x.amount_bin),[{label:'Transactions',data:d.distribution.map(x=>x.transaction_count),backgroundColor:'#e7894b',borderRadius:3}],{scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{grid:{color:'#edf1f0'}}}});
 if(document.getElementById('hour-chart'))chart('hour-chart','bar',d.hourly.map(x=>String(x.transaction_hour).padStart(2,'0')), [{label:'Transactions',data:d.hourly.map(x=>x.transaction_count),backgroundColor:'#0c7773',borderRadius:3}],{scales:{x:{grid:{display:false}},y:{grid:{color:'#edf1f0'}}}});
 if(document.getElementById('stats-panel'))document.getElementById('stats-panel').parentElement.innerHTML=`<div class="panel-head"><div><h2>Percentile profile</h2><p>Distribution evidence for the average-versus-median gap.</p></div></div><div class="table-wrap"><table class="data-table"><tbody><tr><td>Minimum</td><td>${money(d.kpis.min_value)}</td></tr><tr><td>25th percentile</td><td>${money(d.quality.percentiles_inr['25'])}</td></tr><tr><td>Median / 50th</td><td>${money(d.quality.percentiles_inr['50'])}</td></tr><tr><td>75th percentile</td><td>${money(d.quality.percentiles_inr['75'])}</td></tr><tr><td>90th percentile</td><td>${money(d.quality.percentiles_inr['90'])}</td></tr><tr><td>95th percentile</td><td>${money(d.quality.percentiles_inr['95'])}</td></tr><tr><td>99th percentile</td><td>${money(d.quality.percentiles_inr['99'])}</td></tr><tr><td>Maximum</td><td>${money(d.kpis.max_value)}</td></tr></tbody></table></div>`;
}
document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===button));render()}));load().catch(error=>{document.getElementById('app').innerHTML=`<div class="loading">Unable to load dashboard data. Run <strong>python scripts/build_analytics.py</strong> first.<br>${esc(error.message)}</div>`});
